# Generated by Django 3.2.12 on 2022-03-03 16:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('meta_and_inheritance', '0002_auto_20220303_1054'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderedworker',
            options={'ordering': ('startwork_date', 'last_name')},
        ),
        migrations.AlterField(
            model_name='worker',
            name='startwork_date',
            field=models.DateField(default=django.utils.timezone.now, null=True, verbose_name='Дата выхода на работу'),
        ),
    ]
