# Generated by Django 3.2.12 on 2022-03-03 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta_and_inheritance', '0002_auto_20220303_1054'),
    ]

    operations = [
        migrations.RunSQL(
            'CREATE INDEX "workers_last_name_92d15c6f" '
            'ON "workers" ("last_name");',

            reverse_sql='DROP INDEX "workers_last_name_92d15c6f";'
        ),
    ]
