# Generated by Django 3.2.12 on 2022-03-03 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta_and_inheritance', '0004_alter_orderedworker_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='last_name',
            field=models.CharField(max_length=30, verbose_name='Фамилия'),
        ),
    ]
